package com.models.communication;

public enum ResponseType {
	
	RESPONSE_LOGIN_OK,
	RESPONSE_REGISTER_OK,
	RESPONSE_FRIEND_REQUEST,
	RESPONSE_MESSAGE_DELIVERED,
	RESPONSE_GENERIC,
	RESPONSE_REFRESHONLINE,
	RESPONSE_ADDDETAILS,
	RESPONSE_SAVEMESSAGE

}
